/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/S6spL7DnAS5
 */
import Link from "next/link"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import {
  DropdownMenuTrigger,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu"

export function Banner() {
  return (
    <div className="w-full">
      <nav className="flex h-16 items-center px-4 md:px-6 border-b border-gray-200 dark:border-gray-800">
        <Link className="flex items-center gap-2 font-semibold" href="#">
          <PackageIcon className="h-6 w-6" />
          <span>Bake Inc</span>
        </Link>
        <div className="flex-1" />
        <Link
          className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 border-gray-200 bg-white px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-gray-50 hover:text-gray-900 focus:bg-gray-50 focus:text-gray-900 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50"
          href="#"
        >
          Contact Sales
        </Link>
        <Link
          className="inline-flex h-9 ml-2 items-center justify-center rounded-md bg-gray-100 px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-200 hover:text-gray-900 focus:bg-gray-200 focus:text-gray-900 focus:outline-none dark:bg-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50"
          href="#"
        >
          Order
        </Link>
        <Link
          className="inline-flex h-9 ml-2 items-center justify-center rounded-md bg-gray-100 px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-200 hover:text-gray-900 focus:bg-gray-200 focus:text-gray-900 focus:outline-none dark:bg-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50"
          href="#"
        >
          Product
        </Link>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Link
              className="inline-flex h-9 ml-4 items-center gap-2 rounded-full border border-gray-200 border-gray-200 bg-white px-3.5 py-3.5 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950"
              href="#"
            >
              <Avatar className="h-7 w-7">
                <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
                <AvatarFallback>A</AvatarFallback>
                <span className="sr-only">A</span>
              </Avatar>
              <span className="text-sm font-medium">A</span>
            </Link>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem>My Orders</DropdownMenuItem>
            <DropdownMenuItem>Address</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Login/Logout</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </nav>
      <section className="w-full pt-12">
        <div className="container px-4">
          <div className="relative grid items-center justify-center gap-4 lg:grid-cols-2 lg:gap-8 xl:gap-12">
            <div className="space-y-4 lg:order-2">
              <h1 className="text-3xl font-bold tracking-tighter md:text-5xl lg:text-6xl/none">
                Uniquely Delicious Cakes
              </h1>
              <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Handcrafted to perfection. Experience the art of sweetness with
                every bite.
              </p>
            </div>
            <img
              alt="Cake"
              className="aspect-[2/1] overflow-hidden rounded-xl object-cover object-center shadow-2xl lg:order-1"
              height="500"
              src="/cakeBanner.jpg"
              width="1000"
            />
          </div>
        </div>
      </section>
    </div>
  )
}

function PackageIcon(props: any) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="cake">
      <path
        fill="none"
        stroke="#303c42"
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M15.5 23.5h.5M19 22.5l.5-.5M23.5 23.5H23M.5 12a2.3 2.3 0 0 0 2 1.5c1.46 0 .79-1.5 3-1.5m10.99-4.7A1.82 1.82 0 0 1 18 5.5c.84 0 2 .72 3.17-.44M2.5 10.5 3 10M4.5 6.5V7M7.5 4l.5.5M11.5 2.5 11 3M14.5 3l.5.5"
      ></path>
      <path
        fill="none"
        stroke="#303c42"
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M12 .5C5.649.5.5 5.649.5 12S5.649 23.5 12 23.5c0-1.29.36-2.58 1.5-3a4.77 4.77 0 0 1 .07-2.2 6.442 6.442 0 0 1-1.57.2 6.51 6.51 0 1 1 5.44-3c.73.09 1.54 0 2.06.46.54-.57 1.15-.5 2-.5.463.006.918.119 1.33.33 2.11-5.973-1.022-12.525-6.995-14.635A11.467 11.467 0 0 0 12 .5z"
      ></path>
    </svg>
  )
}
