/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ywl4YzCr3JE
 */
import { Badge } from "@/components/ui/badge"
import { CardHeader, CardContent, Card } from "@/components/ui/card"

export function Cards() {
  return (
    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
      <Card className="w-full">
        <CardHeader>
          <Badge className="absolute top-2 left-2" variant="secondary">
            50% OFF
          </Badge>
          <img
            alt="KFC"
            className="aspect-video overflow-hidden rounded-t-lg object-cover"
            height={200}
            src="/placeholder.svg"
            width={300}
          />
        </CardHeader>
        <CardContent>
          <div className="flex justify-between items-center">
            <h3 className="text-lg font-bold">KFC</h3>
            <span className="text-sm bg-green-200 text-green-800 px-2 py-1 rounded">4.1</span>
          </div>
          <p className="text-sm text-gray-600">Burger, Fast Food, Biryani...</p>
          <div className="flex justify-between items-center mt-2">
            <span className="text-lg font-semibold">₹400 for one</span>
            <span className="text-sm text-gray-500">26 min</span>
          </div>
          <p className="text-xs text-gray-500 mt-2">Follows all Max Safety measures to ensure your food is safe</p>
        </CardContent>
      </Card>
      <Card className="w-full">
        <CardHeader>
          <Badge className="absolute top-2 left-2" variant="secondary">
            50% OFF
          </Badge>
          <img
            alt="McDonald's"
            className="aspect-video overflow-hidden rounded-t-lg object-cover"
            height={200}
            src="/placeholder.svg"
            width={300}
          />
        </CardHeader>
        <CardContent>
          <div className="flex justify-between items-center">
            <h3 className="text-lg font-bold">McDonald's</h3>
            <span className="text-sm bg-green-200 text-green-800 px-2 py-1 rounded">4.3</span>
          </div>
          <p className="text-sm text-gray-600">Burger, Wraps, Fast Food...</p>
          <div className="flex justify-between items-center mt-2">
            <span className="text-lg font-semibold">₹400 for one</span>
            <span className="text-sm text-gray-500">25 min</span>
          </div>
          <p className="text-xs text-gray-500 mt-2">Follows all Max Safety measures to ensure your food is safe</p>
        </CardContent>
      </Card>
      <Card className="w-full">
        <CardHeader>
          <Badge className="absolute top-2 left-2" variant="secondary">
            10% OFF
          </Badge>
          <img
            alt="Omno's Pizza"
            className="aspect-video overflow-hidden rounded-t-lg object-cover"
            height={200}
            src="/placeholder.svg"
            width={300}
          />
        </CardHeader>
        <CardContent>
          <div className="flex justify-between items-center">
            <h3 className="text-lg font-bold">Omno's Pizza</h3>
            <span className="text-sm bg-green-200 text-green-800 px-2 py-1 rounded">4.3</span>
          </div>
          <p className="text-sm text-gray-600">Pizza, Fast Food</p>
          <div className="flex justify-between items-center mt-2">
            <span className="text-lg font-semibold">₹400 for one</span>
            <span className="text-sm text-gray-500">30 min</span>
          </div>
          <p className="text-xs text-gray-500 mt-2">Follows all Max Safety measures to ensure your food is safe</p>
        </CardContent>
      </Card>
      <Card className="w-full">
        <CardHeader>
          <Badge className="absolute top-2 left-2" variant="secondary">
            50% OFF
          </Badge>
          <img
            alt="Khan's Kathi Rolls"
            className="aspect-video overflow-hidden rounded-t-lg object-cover"
            height={200}
            src="/placeholder.svg"
            width={300}
          />
        </CardHeader>
        <CardContent>
          <div className="flex justify-between items-center">
            <h3 className="text-lg font-bold">Khan's Kathi Rolls</h3>
            <span className="text-sm bg-green-200 text-green-800 px-2 py-1 rounded">4.1</span>
          </div>
          <p className="text-sm text-gray-600">Rolls, Chinese, Mughlai</p>
          <div className="flex justify-between items-center mt-2">
            <span className="text-lg font-semibold">₹400 for one</span>
            <span className="text-sm text-gray-500">24 min</span>
          </div>
          <p className="text-xs text-gray-500 mt-2">Follows all Max Safety measures to ensure your food is safe</p>
        </CardContent>
      </Card>
      <Card className="w-full">
        <CardHeader>
          <Badge className="absolute top-2 left-2" variant="secondary">
            50% OFF
          </Badge>
          <img
            alt="Domino's Pizza"
            className="aspect-video overflow-hidden rounded-t-lg object-cover"
            height={200}
            src="/placeholder.svg"
            width={300}
          />
        </CardHeader>
        <CardContent>
          <div className="flex justify-between items-center">
            <h3 className="text-lg font-bold">Domino's Pizza</h3>
            <span className="text-sm bg-green-200 text-green-800 px-2 py-1 rounded">4.0</span>
          </div>
          <p className="text-sm text-gray-600">Pizza, Fast Food, Beverages...</p>
          <div className="flex justify-between items-center mt-2">
            <span className="text-lg font-semibold">₹400 for one</span>
            <span className="text-sm text-gray-500">25 min</span>
          </div>
          <p className="text-xs text-gray-500 mt-2">Follows all Max Safety measures to ensure your food is safe</p>
        </CardContent>
      </Card>
      <Card className="w-full">
        <CardHeader>
          <Badge className="absolute top-2 left-2" variant="secondary">
            50% OFF
          </Badge>
          <img
            alt="Desi Galli"
            className="aspect-video overflow-hidden rounded-t-lg object-cover"
            height={200}
            src="/placeholder.svg"
            width={300}
          />
        </CardHeader>
        <CardContent>
          <div className="flex justify-between items-center">
            <h3 className="text-lg font-bold">Desi Galli</h3>
            <span className="text-sm bg-green-200 text-green-800 px-2 py-1 rounded">3.8</span>
          </div>
          <p className="text-sm text-gray-600">North Indian, Chinese, Biryani...</p>
          <div className="flex justify-between items-center mt-2">
            <span className="text-lg font-semibold">₹400 for one</span>
            <span className="text-sm text-gray-500">32 min</span>
          </div>
          <p className="text-xs text-gray-500 mt-2">Follows all Max Safety measures to ensure your food is safe</p>
        </CardContent>
      </Card>
    </div>
  )
}
