/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SC563PvRNIu
 */

export function Catagories() {
  return (
    <section className="w-full py-12">
      <div className="container flex flex-col items-center gap-4 px-4 md:px-6">
        <div className="flex flex-col items-center gap-2 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Explore Our Categories
          </h2>
          <p className="text-gray-500 md:text-xl/relaxed dark:text-gray-400">
            Discover new topics and interests.
          </p>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-8 items-start w-full max-w-4xl">
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Chocolate Cake"
              className="rounded-full border border-gray-200 object-cover aspect-square dark:border-gray-800"
              height={96}
              src="/chocolatecake.webp"
              width={96}
            />
            <span className="font-semibold">Chocolate Cake</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Carrot Cake"
              className="rounded-full border border-gray-200 object-cover aspect-square dark:border-gray-800"
              height={96}
              src="/carrot.jpeg"
              width={96}
            />
            <span className="font-semibold">Carrot Cake</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Red Velvet Cake"
              className="rounded-full border border-gray-200 object-cover aspect-square dark:border-gray-800"
              height={96}
              src="/RedVelvetCake.jpg"
              width={96}
            />
            <span className="font-semibold">Red Velvet Cake</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Cheesecake"
              className="rounded-full border border-gray-200 object-cover aspect-square dark:border-gray-800"
              height={96}
              src="/cheesecake.jpg"
              width={96}
            />
            <span className="font-semibold">Cheesecake</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Tiramisu"
              className="rounded-full border border-gray-200 object-cover aspect-square dark:border-gray-800"
              height={96}
              src="/tiramisu-square.jpg"
              width={96}
            />
            <span className="font-semibold">Tiramisu</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Cupcakes"
              className="rounded-full border border-gray-200 object-cover aspect-square dark:border-gray-800"
              height={96}
              src="/Cupcakes.webp"
              width={96}
            />
            <span className="font-semibold">Cupcakes</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Pancakes"
              className="rounded-full border border-gray-200 object-cover aspect-square dark:border-gray-800"
              height={96}
              src="/pancake.jpg"
              width={96}
            />
            <span className="font-semibold">Pancakes</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Waffles"
              className="rounded-full border border-gray-200 object-cover aspect-square dark:border-gray-800"
              height={96}
              src="/Waffles.jpg"
              width={96}
            />
            <span className="font-semibold">Waffles</span>
          </div>
        </div>
      </div>
    </section>
  )
}
