/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/istwbewz1qt
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Footer() {
  return (
    <footer className="bg-gray-50 dark:bg-gray-950">
      <div className="container grid gap-6 px-4 py-12 md:grid-cols-2 md:py-16 lg:px-6 lg:gap-10">
        <div className="flex items-center space-x-2">
          <ChevronRightIcon className="h-4 w-4 text-gray-500" />
          <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Sweet Delights</h2>
        </div>
        <div className="grid gap-2 text-sm">
          <p className="text-gray-500">The best place to find delicious cakes for any occasion.</p>
          <form className="flex space-x-2">
            <Input className="max-w-sm flex-1" placeholder="Enter your email" type="email" />
            <Button type="submit">Subscribe</Button>
          </form>
        </div>
        <div className="grid gap-2 text-sm">
          <ul className="flex flex-col gap-2 text-sm">
            <li>
              <Link className="font-medium hover:underline underline-offset-4" href="#">
                Home
              </Link>
            </li>
            <li>
              <Link className="font-medium hover:underline underline-offset-4" href="#">
                About
              </Link>
            </li>
            <li>
              <Link className="font-medium hover:underline underline-offset-4" href="#">
                Products
              </Link>
            </li>
            <li>
              <Link className="font-medium hover:underline underline-offset-4" href="#">
                Contact
              </Link>
            </li>
          </ul>
        </div>
        <div className="grid gap-2 text-sm">
          <div className="flex items-center space-x-2">
            <MailIcon className="h-4 w-4 text-gray-500" />
            <span className="font-medium text-gray-500">Email: </span>
            <span className="font-medium">info@sweetdelights.com</span>
          </div>
          <div className="flex items-center space-x-2">
            <PhoneIcon className="h-4 w-4 text-gray-500" />
            <span className="font-medium text-gray-500">Call us: </span>
            <span className="font-medium">1-800-123-4567</span>
          </div>
        </div>
        <div className="grid gap-2 text-sm">
          <p className="text-gray-500">Connect with us on social media to stay updated on our latest offers.</p>
          <div className="flex gap-2">
            <Link
              className="rounded-full border border-gray-200 border-gray-200 overflow-hidden dark:border-gray-800"
              href="#"
            >
              <FacebookIcon className="w-4 h-4 bg-facebook p-2 rounded-full text-sm sr-only" />
              <span className="sr-only">Facebook</span>
            </Link>
            <Link
              className="rounded-full border border-gray-200 border-gray-200 overflow-hidden dark:border-gray-800"
              href="#"
            >
              <InstagramIcon className="w-4 h-4 bg-instagram p-2 rounded-full text-sm sr-only" />
              <span className="sr-only">Instagram</span>
            </Link>
            <Link
              className="rounded-full border border-gray-200 border-gray-200 overflow-hidden dark:border-gray-800"
              href="#"
            >
              <TwitterIcon className="w-4 h-4 bg-twitter p-2 rounded-full text-sm sr-only" />
              <span className="sr-only">Twitter</span>
            </Link>
            <Link
              className="rounded-full border border-gray-200 border-gray-200 overflow-hidden dark:border-gray-800"
              href="#"
            >
              <YoutubeIcon className="w-4 h-4 bg-youtube p-2 rounded-full text-sm sr-only" />
              <span className="sr-only">YouTube</span>
            </Link>
            <Link
              className="rounded-full border border-gray-200 border-gray-200 overflow-hidden dark:border-gray-800"
              href="#"
            >
              <LinkedinIcon className="w-4 h-4 bg-linkedin p-2 rounded-full text-sm sr-only" />
              <span className="sr-only">LinkedIn</span>
            </Link>
          </div>
        </div>
      </div>
      <div className="border-t border-gray-200 border-gray-200 dark:border-gray-800">
        <div className="container flex justify-between items-center h-14 px-4 md:px-6">
          <nav className="flex gap-4">
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
              Terms & Conditions
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
              Privacy Policy
            </Link>
          </nav>
          <div className="text-sm text-gray-500 dark:text-gray-400">© 2024 Sweet Delights. All rights reserved.</div>
        </div>
      </div>
    </footer>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function YoutubeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}
