/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/k1RN23QzJvb
 */
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"

export function Signup() {
  return (
    <div className="flex flex-col min-h-screen">
      <div className="flex items-center p-4">
        <div className="container flex items-center gap-4 px-4 py-2">
          <Link className="flex items-center gap-2" href="#">
            <HomeIcon className="h-6 w-6" />
            <span className="font-semibold">Home</span>
          </Link>
          <nav className="ml-auto space-x-4">
            <Link
              className="font-medium rounded-md px-2 py-1 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
              href="#"
            >
              Home
            </Link>
            <Link
              className="font-medium rounded-md px-2 py-1 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
              href="#"
            >
              Blog
            </Link>
            <Link
              className="font-medium rounded-md px-2 py-1 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
              href="#"
            >
              About
            </Link>
            <Link
              className="font-medium rounded-md px-2 py-1 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
              href="#"
            >
              Contact
            </Link>
          </nav>
        </div>
      </div>
      <div className="flex-1 flex items-center justify-center p-4">
        <div className="w-full max-w-sm space-y-4">
          <div className="space-y-2 text-center">
            <h1 className="text-3xl font-bold">Sign In</h1>
            <p className="text-gray-500 dark:text-gray-400">
              Sign in to your account
            </p>
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="m@example.com" type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input id="password" type="password" />
          </div>
          <Button className="w-full">Sign In</Button>
          <div className="flex items-center space-x-2">
            <Checkbox id="remember-me" />
            <Label className="text-sm" htmlFor="remember-me">
              Remember me
            </Label>
          </div>
          <div className="grid gap-2">
            <Button className="w-full" variant="outline">
              Sign in with Google
            </Button>
            <Button className="w-full" variant="outline">
              Sign in with Facebook
            </Button>
            <Button className="w-full" variant="outline">
              Sign in with Apple
            </Button>
          </div>
          <div className="text-center">
            <Link className="text-sm underline" href="#">
              Forgot your password?
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

function HomeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}
